### ISSUE TITLE
绍兴体彩

### ISSUE THREAD

**Issue by pengneal** [yml2213/javascript#9]
获取的cookies 每次只能管半天左右，请问老大您是如何解决的呢？
还有这个东西有圈X教程吗？

**Comment by yml2213** [comment]
你抓得有问题吧，我的很久没掉了
圈x兼容懒得写了，自己改下脚本就行

**Comment by pengneal** [comment]
抓的Authori-zation 后面的内容。
难不成是因为我抓了后 又手动进入了之前的就不能用了？
